# This is a basic workflow to help you get started with Actions
name: Build on push master

on:
  push:
    branches: [ linux-fixes ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: avantgarde280/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Tk5
      with:
        arch: arm
        compiler: gcc/7
        defconfig: ouya_linux_defconfig
        image: zImage

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: "543221957" 
        #${{ secrets.CHANNEL_ID }}
        token: "2049951634:AAH9bKEiRZQdnTJ-EJm0U1O8H2WNa7R1KS8"
        #${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
